---
apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rouge            
  namespace: demo
data:
  IP: "192.168.0.24"
  PORT:	"80"
---
---
apiVersion: v1
kind: Pod
metadata:
  name: xerxex
  labels:
    app: ddos
  namespace: "demo"

spec:
  containers:
  - name: rouge-1
    image: xerxes
    env:
      - name: IP
        valueFrom:
          configMapKeyRef:
            name: rouge
            key: IP
      - name: PORT
        valueFrom:
          configMapKeyRef:
            name: rouge
            key: PORT
  - name: rouge-2 
    image: xerxes
    env:
      - name: IP
        valueFrom:
          configMapKeyRef:
            name: rouge
            key: IP
      - name: PORT
        valueFrom:
          configMapKeyRef:
            name: rouge
            key: PORT
  - name: rouge-3 
    image: xerxes
    env:
      - name: IP
        valueFrom:
          configMapKeyRef:
            name: rouge
            key: IP
      - name: PORT
        valueFrom:
          configMapKeyRef:
            name: rouge
            key: PORT
  - name: rouge-4 
    image: xerxes
    env:
      - name: IP
        valueFrom:
          configMapKeyRef:
            name: rouge
            key: IP
      - name: PORT
        valueFrom:
          configMapKeyRef:
            name: rouge
            key: PORT
  - name: rouge-5 
    image: xerxes
    env:
      - name: IP
        valueFrom:
          configMapKeyRef:
            name: rouge
            key: IP
      - name: PORT
        valueFrom:
          configMapKeyRef:
            name: rouge
            key: PORT
  - name: rouge-6 
    image: xerxes
    env:
      - name: IP
        valueFrom:
          configMapKeyRef:
            name: rouge
            key: IP
      - name: PORT
        valueFrom:
          configMapKeyRef:
            name: rouge
            key: PORT
  - name: rouge-7 
    image: xerxes
    env:
      - name: IP
        valueFrom:
          configMapKeyRef:
            name: rouge
            key: IP
      - name: PORT
        valueFrom:
          configMapKeyRef:
            name: rouge
            key: PORT
  - name: rouge-8 
    image: xerxes
    env:
      - name: IP
        valueFrom:
          configMapKeyRef:
            name: rouge
            key: IP
      - name: PORT
        valueFrom:
          configMapKeyRef:
            name: rouge
            key: PORT
  - name: rouge-9
    image: xerxes
    env:
      - name: IP
        valueFrom:
          configMapKeyRef:
            name: rouge
            key: IP
      - name: PORT
        valueFrom:
          configMapKeyRef:
            name: rouge
            key: PORT
  - name: rouge-10 
    image: xerxes
    env:
      - name: IP
        valueFrom:
          configMapKeyRef:
            name: rouge
            key: IP
      - name: PORT
        valueFrom:
          configMapKeyRef:
            name: rouge
            key: PORT
---
